app:
  scheduler:
    enable: true
    interval: 10000
    force-check-delay: 10000

  client-base-url:
    github-url: https://api.github.com
    stackoverflow-url: https://api.stackexchange.com
    bot-url: http://localhost:8090

spring:
  application:
    name: scrapper

springdoc:
  swagger-ui:
    path: "/swagger-ui"
  override-with-generic-response: false

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
